[bilidanmu]
room_id = 23891811

[sc2client]
red_player = 4
blue_player = 3
game_maps = [
    "Custom/StarArena.SC2Map",
    "Custom/StarArena1.SC2Map",
]
director_name = "GM"
audience_name = "SYSTEM"

[msq]
cmd_queue_cap = 100
msg_queue_cap = 100

[state]
player_cap = 20
join_cap = 100